Arrangementen toegevoegd
Digital-Architects-Avans/dotnetflix pull request #26
Opened 2024-03-10 12:40 UTC by VanHamsteren

PR om arrangementen aan de bestelpagina toe te voegen

2024-03-10 15:00 UTC, AlexVDV116 commented on dotnetflix.Api/Properties/ServiceDependencies/local/mssql1.arm.json
Dit bestand niet toevoegen aan je VCS.

2024-03-10 15:00 UTC, AlexVDV116 commented on dotnetflix.Api/Properties/serviceDependencies.json
Dit bestand niet toevoegen aan je VCS.

2024-03-10 15:00 UTC, AlexVDV116 commented on dotnetflix.Api/Properties/serviceDependencies.local.json
Dit bestand niet toevoegen aan je VCS.

2024-03-10 15:09 UTC, AlexVDV116 commented on dotnetflix.Api/dotnetflix.Api.csproj
> +    <UserSecretsId>d89e109e-eeaa-44f9-b827-e46891a2642d</UserSecretsId>
Wat doet deze Id?

2024-03-10 15:14 UTC, AlexVDV116 commented on dotnetflix.Web/Pages/Checkout/CheckoutPage.razor
> +@inject IOrderOptionsService OrderOptionsService
DI in je code behind

2024-03-10 15:15 UTC, AlexVDV116 commented on dotnetflix.Web/Services/Contracts/IOrderOptionsService.cs
Waarom maak je hier een Service voor aan? Waarom kan dit niet in de TicketsService?

2024-03-10 15:17 UTC, AlexVDV116 commented on dotnetflix.Web/Pages/Tickets/TicketsPage.razor
> +@inject IOrderOptionsService OrderOptionsService
DI in je code behind zoals afgesproken

2024-03-10 15:18 UTC, AlexVDV116 requested changes
Heb een aantal comments waarbij ik graag nog wat changes zou zien.

2024-03-10 15:27 UTC, AlexVDV116 commented on dotnetflix.Web/Pages/Checkout/CheckoutPage.razor
> +                                // Adjust grandTotal based on arrangements
Waarom pas je hier nogmaals logica toe voor het berekenen van een prijs. Deze logica past beter in de OrderService, waar al logica bestaat voor het berekenen van ticketprices. 

Ook kun je dan een arrangement per ticket berekenen als dezelfde logica volgt.

2024-03-10 17:16 UTC, vderlinden commented on dotnetflix.Web/Pages/Tickets/TicketsPage.razor
> +            //ChildDiscountAvailable = Movie.SpokenLanguages == "NL" && SelectedShow.Date.TimeOfDay.Hours < 18;
Ik kan dit in de huidige branch niet controleren, maar kijk ik er overheen of wordt ChildDiscountAvailable nu niet geset? En krijg je dus nooit de optie om een ticket met kinder korting te kopen?

2024-03-10 17:16 UTC, vderlinden commented on dotnetflix.Web/Services/Contracts/IOrderOptionsService.cs
En waarom zit deze file in de commit '[Merge with main](https://github.com/Digital-Architects-Avans/dotnetflix/pull/26/commits/e2daf943b6db8069638e5e9a86ff89d5b719d616)'

2024-03-10 17:20 UTC, vderlinden reviewed
Branch getest en nieuwe functionaliteit werkt.
Alex heeft e.e.a. juist opgemerkt.
Ik vind het een beetje verwarrend dat je changes (lees: nieuwe code) hebt toegevoegd in een commit die Merge with main heet. Erg lastig om nu te volgen wat je gedaan hebt met 2 commits in totaal. Maak sowieso een 'merge commit' als je main binnen haalt please. Dan ziet Git ook dat we die bestanden niet hoeven te beoordelen/reviewen.

2024-03-10 19:32 UTC, VanHamsteren commented on dotnetflix.Api/dotnetflix.Api.csproj
> +    <UserSecretsId>d89e109e-eeaa-44f9-b827-e46891a2642d</UserSecretsId>
Kwam deze met mijn PR mee? Ik heb geen idee waar deze vandaan komt

2024-03-10 20:33 UTC, VanHamsteren commented on dotnetflix.Api/Properties/ServiceDependencies/local/mssql1.arm.json
Toegevoegd aan ignore aan mijn kant

2024-03-10 20:33 UTC, VanHamsteren commented on dotnetflix.Api/Properties/serviceDependencies.json
Toegevoegd aan ignore aan mijn kant

2024-03-10 20:33 UTC, VanHamsteren commented on dotnetflix.Api/Properties/serviceDependencies.local.json
Toegevoegd aan ignore aan mijn kant

2024-03-10 20:36 UTC, VanHamsteren commented on dotnetflix.Web/Services/Contracts/IOrderOptionsService.cs
Mijn idee was om logica te splitsen om geen interfaces te maken die meerdere dingen kunnen afhandelen (SOLID)

2024-03-12 07:36 UTC, AlexVDV116 commented on dotnetflix.Web/Services/Contracts/IOrderOptionsService.cs
Logica te splitsen? Welke logica? 3 boolean variabelen? Die betrekking hebben op bestaande logica in een bestaande OrderService?

2024-03-13 18:03 UTC, closed without merging