Updated Data\Entities
Digital-Architects-Avans/dotnetflix pull request #4
Opened 2024-02-25 20:32 UTC by VanHamsteren

Added Tickets,Seats
Added TicketDto

2024-02-26 10:24 UTC, vderlinden approved these changes

2024-02-26 10:24 UTC, vderlinden commented on dotnetflix.Models/Dtos/Ticket/TicketDto.cs
> +	ThreeD = 5,             // Addition: 2.50 for 3D movies
@VanHamsteren Maybe 3D should be a separate value? You can't show tickets for a seniors that want to go to a 3D film now, or do I miss something?

2024-02-26 14:29 UTC, Brian174tech requested changes
Mijn voorstel zou zijn om de Ticket enkel naar een voorstelling en een stoel te laten verwijzen dmv een foreignkey. Nu koppel je alle entiteiten op data niveau terwijl de theater en movie informatie al in de voorstelling zitten - is dus dubbel. Ook de properties van andere entiteiten zou ik niet opnemen in de ticket entiteit deze kan je ophalen doormiddel van de foreignkey verwijzing naar het andere entiteit en die aan te spreken. Op de dto niveau kan je dit natuurlijk allemaal wel doen.

2024-02-28 12:33 UTC, AlexVDV116 requested changes
Ik heb zojuist nog even goed gekeken naar het ERD en de logica van bepaalde entiteiten en properties en ben van mening dat we hier nog even goed naar moeten kijken. Het is belangrijk dit dit goed staat. Dus stel voor nog even te wachten met het mergen van deze PR totdat alle entiteiten definitief zijn.

2024-02-28 21:07 UTC, closed without merging