Added Ticket API
Digital-Architects-Avans/dotnetflix pull request #5
Opened 2024-02-25 21:26 UTC by VanHamsteren

For Ticket entity, added:
- Repository
- DTO
- Service
- Controller
- Mapper

2024-02-26 10:32 UTC, vderlinden approved these changes
Good work. I didn't test te code fully, but it looks to be all there. Nice!

2024-02-26 10:32 UTC, vderlinden commented on dotnetflix.Models/Dtos/Ticket/TicketDto.cs
> +	ThreeD = 5,             // Addition: 2.50 for 3D movies
@VanHamsteren Same [here](https://github.com/Digital-Architects-Avans/dotnetflix/pull/4), though its possible to set BasePrice based op MovieRuntime. Maybe just remove ThreeD from Discount enum?

2024-02-26 17:25 UTC, AlexVDV116 commented on dotnetflix.Api/Controllers/TicketController.cs
> +			var tickets		= await _ticketRepository.GetTickets();
formatting

2024-02-26 17:39 UTC, AlexVDV116 commented on dotnetflix.Api/Data/DbContext.cs
> +			/* De bioscoop bestaat uit 6 zalen: 3 grote zalen (1 tot en met 3) en 3 kleine (4 tot en met 6).
Deze comments zijn onnodig, dit staat in de requirements en willen we niet in de code hebben.

2024-02-26 17:40 UTC, AlexVDV116 commented on dotnetflix.Api/Data/Entities/Seat.cs
> + * De bioscoop bestaat uit 6 zalen: 3 grote zalen (1 tot en met 3) en 3 kleine (4 tot en met 6).
wederom onnodige comments

2024-02-26 17:42 UTC, AlexVDV116 commented on dotnetflix.Api/Data/Entities/Ticket.cs
Ticket versimpelen en enkel naar een show en seat laten verwijzen.

2024-02-26 17:44 UTC, AlexVDV116 requested changes
Ik denk dat we inderdaad even moeten kijken naar de Ticket constructie, er zijn nu veel dubbele properties in verschillende entiteiten. Ticket kan naar een Show en een Seat verwijzen, en vanuit hier kan alle benodigde informatie over die seat of show opgehaald worden.

Verder nog wat formatting en onnodige comments.

Controller ziet er voor de rest netjes uit, mogelijk dat je hier in een later stadia nog kan optimaliseren door middel van een Include op repository niveau, scheelt je behoorlijk wat queries.

2024-02-28 18:14 UTC, Brian174tech requested changes
Eerste voorgaande PR op orde maken

2024-02-28 20:36 UTC, VanHamsteren commented
Feedback is verwerkt

2024-02-28 21:07 UTC, closed without merging